### ISSUE TITLE
Upgrade required [Error]

### ISSUE THREAD

**Issue by GrumpyOet** [iiegor/slither#2]
if i go to localhost:8080 (8080 is the port of the server) the stays Upgrade Required

So how to fix that (or join it)

**Comment by iiegor** [comment]
It isn't an error, just means that the server is running and can be accesed through `ws://localhost:8080`. In order to be able to connect to your local server and "test" it you'll need a client. You can use the original one from [slither.io](slither.io), just go there, open the console, paste: `sos = [{ ip: "localhost", po: 8080, ac: 34, ptm: 121 }]` and press the play button.

Anyway, the server is on active development so don't expect a working game right now.

**Comment by fakeusername1029391323** [comment]
Will there eventually be a client made so we dont have to use the slither.io url?

**Comment by Jay-kch** [comment]
I have the same issue .Can anyone with the solution help?I am not able to open it up on chrome.

**Comment by thapakazi** [comment]
Above workaround, didn't work @iiegor :disappointed:

**Comment by thapakazi** [comment]
Here is what I get with `nmap...`

```
8080/tcp open  http-proxy
|_http-title: Site doesn't have a title (text/plain).
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at https://nmap.org/cgi-bin/submit.cgi?new-service :
SF-Port8080-TCP:V=7.12%I=7%D=9/25%Time=57E7C9AE%P=x86_64-unknown-linux-gnu
SF:%r(GetRequest,97,"HTTP/1\.1\x20426\x20Upgrade\x20Required\r\nContent-Le
SF:ngth:\x2016\r\nContent-Type:\x20text/plain\r\nDate:\x20Sun,\x2025\x20Se
SF:p\x202016\x2012:57:18\x20GMT\r\nConnection:\x20close\r\n\r\nUpgrade\x20
SF:Required")%r(HTTPOptions,97,"HTTP/1\.1\x20426\x20Upgrade\x20Required\r\
SF:nContent-Length:\x2016\r\nContent-Type:\x20text/plain\r\nDate:\x20Sun,\
SF:x2025\x20Sep\x202016\x2012:57:18\x20GMT\r\nConnection:\x20close\r\n\r\n
SF:Upgrade\x20Required")%r(FourOhFourRequest,97,"HTTP/1\.1\x20426\x20Upgra
SF:de\x20Required\r\nContent-Length:\x2016\r\nContent-Type:\x20text/plain\
SF:r\nDate:\x20Sun,\x2025\x20Sep\x202016\x2012:57:18\x20GMT\r\nConnection:
SF:\x20close\r\n\r\nUpgrade\x20Required");

```
